# Generated by Django 5.2.8 on 2025-11-24 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0006_cargar_preguntas_test_completo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contenidopersonalizado',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Contenido Personalizado', 'verbose_name_plural': 'Contenidos Personalizados'},
        ),
        migrations.RemoveField(
            model_name='recurso',
            name='url',
        ),
        migrations.AddField(
            model_name='contenidopersonalizado',
            name='esta_activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contenidopersonalizado',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='contenido_personalizado/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'mp4', 'avi', 'mov'])]),
        ),
        migrations.AlterField(
            model_name='contenidopersonalizado',
            name='url',
            field=models.URLField(blank=True, verbose_name='URL del contenido'),
        ),
    ]
