# Generated by Django 5.2.8 on 2025-11-27 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0007_alter_contenidopersonalizado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='recurso',
            name='duracion',
            field=models.IntegerField(default=0, help_text='Duración del recurso en minutos', verbose_name='Duración (minutos)'),
        ),
        migrations.AddField(
            model_name='recurso',
            name='es_embed',
            field=models.BooleanField(default=False, help_text='Marcar si el contenido se puede incrustar', verbose_name='¿Es contenido embed?'),
        ),
    ]
